In [38]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
art = pd.read_csv("Art.csv")
artHood = art.groupby("neighborhood").count().reset_index()
artHood
n = 0
neighbor = ''
count = 0
while(n<len(artHood)):
    if(artHood.iloc[n][1] > count):
        neighbor = artHood.iloc[n][0]
        count = artHood.iloc[n][1]
    n = n+1

print(neighbor)

Central Business District

In [31]:
art.head(10)

,id,name,title,artist_name,art_type,park,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone,latitude,longitude
0,812728309,1001,Oakwood Road Monument,NaN,NaN,NaN,Oakwood,2.0,28.0,4.200356e+10,5.0,28.0,6.0,1-19,40.429192,-80.066225
1,2032091917,129,Middle East Memorial Plaque,NaN,War Memorials,NaN,Central Business District,6.0,1.0,4.200302e+10,6.0,1.0,2.0,1-4,40.438092,-79.996852
2,1447629273,143,L'Enfant,Paul Roger-Bloche,Historic Art,NaN,Carrick,4.0,29.0,4.200329e+10,3.0,29.0,3.0,4-23,40.388748,-79.986497
3,1935017944,148,Veterans Memorial (Brookline),Not Applicable,War Memorials,Brookline Monument,Brookline,4.0,19.0,4.200319e+10,5.0,19.0,6.0,4-26,40.391721,-80.016981
4,752311791,153,Oakley Street Mosaic Steps,Laura Jean McLaughlin,Modern and Contemporary Art,NaN,South Side Slopes,3.0,16.0,4.200316e+10,3.0,16.0,3.0,4-24,40.423580,-79.968693
5,915929762,156,Windows of Light,Jane Haskell,Modern and Contemporary Art,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,275033545,157,Time Travelers,Edith Abeyta & Sandy Kessler Kaminski,Modern and Contemporary Art,NaN,Hazelwood,5.0,15.0,4.200356e+10,3.0,15.0,4.0,2-13,40.406833,-79.944514
7,687548560,159,Untitled (Ben Grubb),Ben Grubb,Modern and Contemporary Art,Highland Park,Highland Park,7.0,11.0,4.200398e+10,2.0,11.0,5.0,3-9,40.481455,-79.911319
8,2095627492,160,Residents of Schenley Park,Nicole Reading,Modern and Contemporary Art,Schenley Park,Squirrel Hill South,5.0,14.0,4.200398e+10,3.0,14.0,4.0,2-8,40.431529,-79.944815
9,1980433881,161,Caves,Randi Stewart,Modern and Contemporary Art,Frick Park,Squirrel Hill South,5.0,14.0,4.200398e+10,3.0,14.0,4.0,2-21,40.429959,-79.914858

In [35]:
artHood.head(10)

,neighborhood,id,name,title,artist_name,art_type,park,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone,latitude,longitude
0,Allegheny Center,18,18,18,17,18,11,18,18,18,18,18,18,18,18,18
1,Allegheny West,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,Allentown,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
3,Beechview,5,5,5,1,5,5,5,5,5,5,5,5,5,5,5
4,Beltzhoover,3,3,3,1,3,3,3,3,3,3,3,3,3,3,3
5,Bloomfield,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,Brighton Heights,5,5,5,2,5,5,5,5,5,5,5,5,5,5,5
7,Brookline,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2
8,Carrick,3,3,3,2,3,1,3,3,3,3,3,3,3,3,3
9,Central Business District,27,27,27,21,27,4,27,27,27,27,27,27,27,27,27